site_name: ReIDHub
repo_url: https://github.com/vickruto/reidhub
site_url: https://vickruto.github.io/reidhub
repo_name: reidhub

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7  # Sun icon for light mode
        name: Switch to dark mode    # Tooltip text
    # Palette toggle for dark mode
    - scheme: slate  # Or 'default' for a lighter dark variant
      toggle:
        icon: material/brightness-4  # Moon icon for dark mode
        name: Switch to light mode   # Tooltip text
  features:
    - content.code.copy  # Copy button for code blocks
    - content.tabs       # Support for tabs
    - navigation.top     # Top navigation bar
    - navigation.tracking # Updates URL on scroll
    - navigation.indexes # enable section indexes
    - announce.dismiss
    - content.tooltips
  # logo: assets/images/logo.jpg  # Optional logo
  favicon: assets/images/favicon.ico

docs_dir: docs
markdown_extensions:
  - abbr
  - attr_list          # For image attributes (#only-light, #only-dark)
  - pymdownx.emoji     # Emoji support
  - pymdownx.highlight  # Code highlighting
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:  # Enable MkDocstrings
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            merge_init_into_class: true

            # from ultralytics: 
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
            # --show root headings only when necessary ie many input params : 
            show_root_heading: true 
            separate_signature: true
            line_length: 80
            show_signature_annotations: true
            show_symbol_type_heading: true # insiders
            show_symbol_type_toc: true # insiders
            show_inheritance_diagram: true # insiders
  - exclude:
      glob:
        - overrides/*.html
        - __pycache__/*
        - datasets/**/*.md
        - datasets/render.py
        - hooks/hooks.py

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
      - FAQ: getting-started/faq.md
  - Datasets: 
    - datasets/index.md
    - Great Zebra and Giraffe Count : datasets/gzgc.md
    - Nyala Data : datasets/nyala.md
    - Amur Tigers Reidentification : datasets/gzgc.md
  - Tutorials: 
    - tutorials/index.md
    - Walkthrough Demo: tutorials/2025-09-22-reidhub-checkpoint.ipynb
  - API Reference: 
    # - api/index.md ## TODO: Update this index page
    - Access: api/access.md
    - Assess: api/assess.md
    - Address: api/address.md
  - Contributing: pages/contributing.md
  - Changelog: pages/changelog.md
  - Acknowledgements: pages/acknowledgements.md

hooks:
  - docs/hooks/hooks.py  # resolve relative image tags correctly.
