site_name: ReIDHub
repo_url: https://github.com/vickruto/reidhub
repo_name: reidhub

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7  # Sun icon for light mode
        name: Switch to dark mode    # Tooltip text
    # Palette toggle for dark mode
    - scheme: slate  # Or 'default' for a lighter dark variant
      toggle:
        icon: material/brightness-4  # Moon icon for dark mode
        name: Switch to light mode   # Tooltip text
  features:
    - content.code.copy  # Copy button for code blocks
    - content.tabs       # Support for tabs
    - navigation.top     # Top navigation bar
    - navigation.tracking # Updates URL on scroll
    - announce.dismiss
  # logo: assets/images/logo.jpg  # Optional logo
  favicon: assets/images/favicon.ico

docs_dir: docs
markdown_extensions:
  - attr_list          # For image attributes (#only-light, #only-dark)
  - pymdownx.emoji     # Emoji support
  - pymdownx.highlight  # Code highlighting
  - pymdownx.superfences
  - admonition

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:  # Enable MkDocstrings
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            merge_init_into_class: true
  - exclude:
      glob:
        - overrides/*.html
        - __pycache__/*

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
      - FAQ: getting-started/faq.md
  - Features:
      - Feature 1: features/feature1.md
      - Feature 2: features/feature2.md
  - Datasets: 
      - Great Zebra and Giraffe Count : output-dataset-readmes/gzgc.md
      - Nyala Data : output-dataset-readmes/nyala.md
      - Amur Tigers Reidentification : output-dataset-readmes/gzgc.md

  - Tutorials: tutorials/index.md
  - API Reference: api/index.md
  - Contributing: contributing.md
  - Changelog: changelog.md


extra:
  announce:
    dismissible: true
    content: >
      ⚠️ This documentation is still under construction.  
      Please check back later!